apiVersion: v1
kind: Namespace
metadata:
  name: testing

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: testdeploy
  name: testdeploy
  namespace: 
spec:
  replicas: 1
  selector:
    matchLabels:
      run: testdeploy
  strategy: {}
  template:
    metadata:
      labels:
        run: testdeploy
    spec:
      containers:
      - image: sreeharshav/rollingupdate:v4
        name: testdeploy

